[General]
alwaysShowChangelog = false
autoUpdate = false
BGMvolume = 50
checkCompatibilityOnStartup = false
chooseHomeTab = "General"
compatibilityEnabled = false
enableDiscordRPC = false
isDevKit = false
isPS4Pro = false
isTrophyPopupDisabled = false
logFilter = ""
logType = "async"
playBGM = false
showSplash = false
sideTrophy = "right"
trophyNotificationDuration = 6.0
updateChannel = "Release"
userName = "RetroDECK"

[Input]
backButtonBehavior = "left"
cursorHideTimeout = 5
cursorState = 1
isMotionControlsEnabled = true
specialPadClass = 1
useSpecialPad = false
useUnifiedInputConfig = true

[GPU]
allowHDR = false
copyGPUBuffers = false
dumpShaders = false
Fullscreen = false
FullscreenMode = "Windowed"
nullGpu = false
patchShaders = true
screenHeight = 720
screenWidth = 1280
vblankDivider = 1

[Vulkan]
crashDiagnostic = false
gpuId = -1
guestMarkers = false
hostMarkers = false
rdocEnable = false
validation = false
validation_gpu = false
validation_sync = false

[Debug]
CollectShader = false
DebugDump = false
FPSColor = true
isSeparateLogFilesEnabled = false

[Keys]
TrophyKey = ""

[GUI]
addonInstallDir = "$XDG_DATA_HOME/shadps4/installed_addons"
backgroundImageOpacity = 50
elfDirs = []
emulatorLanguage = "en_US"
gameTableMode = 0
geometry_h = 720
geometry_w = 1280
geometry_x = 0
geometry_y = 263
iconSize = 36
iconSizeGrid = 69
installDirs = ["$XDG_DATA_HOME/shadps4/installed_games"]
installDirsEnabled = [true]
loadGameSizeEnabled = true
mw_height = 720
mw_width = 1280
recentFiles = []
saveDataPath = "$rd_home_saves_path/shadps4/saves"
showBackgroundImage = true
sliderPos = 0
sliderPosGrid = 0
theme = 0

[Settings]
consoleLanguage = 1

