RecentROM = []
SlowmoFPS = 30.0
TargetFPS = 60.0
FastForwardFPS = 1000.0
UITheme = ""
AudioSync = false
LimitFPS = true
PauseLostFocus = true

[Instance0]
JoystickID = 0
SavestatePath = "RETRODECKSTATESDIR/nds/melonds"
SaveFilePath = "RETRODECKSAVESDIR/nds/melonds"
EnableCheats = false

[Instance0.Window2]
Enabled = false

[Instance0.Joystick]
HK_GuitarGripBlue = -1
HK_GuitarGripYellow = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_Lid = -1
Y = 3
HK_FrameStep = -1
HK_SolarSensorIncrease = -1
HK_GuitarGripRed = -1
L = 4
R = 5
Up = 257
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = 258
Start = 7
Select = 6
X = 2
B = 1
Down = 260
A = 0
HK_Mic = -1
HK_FastForward = -1
HK_FrameLimitToggle = -1
Left = 264
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
HK_Reset = -1
HK_PowerButton = -1
HK_VolumeDown = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_FastForwardToggle = -1

[Instance0.Keyboard]
HK_GuitarGripBlue = -1
HK_GuitarGripYellow = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_Lid = 134217804
Y = -1
HK_FrameStep = -1
HK_SolarSensorIncrease = 671088683
HK_GuitarGripRed = -1
L = -1
R = -1
Up = -1
HK_FullscreenToggle = 83886084
HK_SlowMo = -1
HK_Pause = 67108944
Right = -1
Start = -1
Select = -1
X = -1
B = -1
Down = -1
A = -1
HK_Mic = 134217808
HK_FastForward = 603979819
HK_FrameLimitToggle = -1
Left = -1
HK_SwapScreens = 83886081
HK_SwapScreenEmphasis = -1
HK_Reset = 67108946
HK_PowerButton = -1
HK_VolumeDown = -1
HK_SolarSensorDecrease = 671088685
HK_VolumeUp = -1
HK_FastForwardToggle = -1

[Instance0.Window3]
Enabled = false

[Instance0.Window0]
Enabled = true
ScreenFilter = false
ShowOSD = true
ScreenAspectTop = 0
IntegerScaling = true
ScreenSizing = 3
ScreenSwap = false
Geometry = "AdnQywADAAAAAAAAAAAAAAAAAv8AAAGhAAAAAAAAAAAAAAL/AAABoQAAAAAAAAAAB4AAAAAAAAAAAAAAAv8AAAGh"
ScreenLayout = 3
ScreenGap = 0
ScreenAspectBot = 0
ScreenRotation = 0

[Instance0.Audio]
DSiVolumeSync = false
Volume = 256

[Instance0.DS]
[Instance0.DS.Battery]
LevelOkay = true

[Instance0.DSi]
[Instance0.DSi.Battery]
Charging = true
Level = 15

[Instance0.Firmware]
FavouriteColour = 0
BirthdayDay = 4
BirthdayMonth = 3
Language = 1
Username = "RetroDECK"
OverrideSettings = false

[Instance0.Window1]
Enabled = false

[Mouse]
HideSeconds = 5
Hide = true

[Mic]
WavPath = ""
Device = ""
InputType = 1

[Savestate]
RelocSRAM = false

[3D]
Renderer = 1

[3D.GL]
BetterPolygons = false
ScaleFactor = 1

[3D.Soft]
Threaded = true

[LAN]
DirectMode = false

[Screen]
VSyncInterval = 1
VSync = false
UseGL = false
Filter = true

[JIT]
FastMemory = true
LiteralOptimisations = true
BranchOptimisations = true
MaxBlockSize = 32
Enable = false

[Audio]
Interpolation = 0

[Emu]
ExternalBIOSEnable = true
DirectBoot = true
ConsoleType = 0

[DS]
FirmwarePath = "RETRODECKBIOSDIR/firmware.bin"
BIOS7Path = "RETRODECKBIOSDIR/bios7.bin"
BIOS9Path = "RETRODECKBIOSDIR/bios9.bin"

[DLDI]
FolderSync = false
ReadOnly = false
ImagePath = "dldi.bin"
ImageSize = 0
Enable = false

[DSi]
NANDPath = ""

[DSi.Camera1]
DeviceName = ""
ImagePath = ""
XFlip = false
InputType = 0

[DSi.Camera0]
DeviceName = ""
ImagePath = ""
XFlip = false
InputType = 0

[DSi.SD]
FolderSync = false
ReadOnly = false
ImagePath = "dsisd.bin"
ImageSize = 0
Enable = false

[MP]
RecvTimeout = 25
AudioMode = 1

